{% set version = "300" %}
{% set build_number = "1" %}

package:
  name: pywin32
  version: {{ version }}

source:
  url: https://github.com/mhammond/pywin32/archive/b{{ version }}.tar.gz
  sha256: 7ce66b7c624c6ca083ed54d81d826ea95268f3e47ece4c811ac086dd9f15b542
  patches:
    - disable_exchange_modules.patch
    - 0003-remove-PATH-pth-hack.patch

{% if build_script == "noop" %}
build:
  number: {{ build_number | int * 2 }}
  noarch: python
  script: echo "noop"

requirements:
  run_constrained:
    # an-impossible-to-satisfy package for a windows install with python
    - vc <=0
  run:
    - python >=3
  host:
    - python >=3
{% elif build_script == "pip" %}
build:
  number: {{ build_number | int * 2 + 1 }}
  script:
    - {{ PYTHON }} setup.py -q install --record=record.txt --skip-verstamp
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %PREFIX%\Lib\site-packages\win32\
    - copy %PREFIX%\Lib\site-packages\pywin32_system32\*.dll %LIBRARY_BIN%\
  skip: true  # [not win or py27]

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
  run:
    - python
{% endif %}

about:
  home: https://github.com/mhammond/pywin32
  license: PSF-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
  description: |
    A set of extension modules that provides access to many of the Windows API functions.
  dev_url: https://github.com/mhammond/pywin32

extra:
  recipe-maintainers:
    - mingwandroid
    - nicoddemus
    - carlodri
